yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='slug'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment', views.add_comment, name='add_comment')
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('group/<slug:slug>/', include('posts.urls', namespace='posts1')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from .validators import validate_not_empty
import datetime
User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='заглавие',
        help_text='напишите заглавие'
    )
    slug = models.SlugField(
        unique=True,
        max_length=20,
        default='title',
        verbose_name='Slug',
        help_text='Установите slug'
    )
    description = models.TextField(
        verbose_name='Описание',
        help_text='Напишите описание'
    )

    def __str__(self):
        return self.title


class Post(models.Model):
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации',
        help_text='Установите дату'
    )
    author = models.ForeignKey(
        User,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Автор',
        help_text='Выберите автора'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу'
    )
    text = models.TextField(
        validators=[validate_not_empty],
        verbose_name='Текст поста',
        help_text='Введите текст поста'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self):
        return self.text[:15]

class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        null=True,
        on_delete=models.SET_NULL,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        null=True,
        on_delete=models.SET_NULL,
        related_name='comments'
    )
    text = models.TextField(
        'Текст',
        help_text='Текст нового комментария'
    )
    created = models.DateTimeField(
        auto_now_add=True
    )

class Follow(models.Model):
    user = models.ForeignKey(
        related_name='follower'
    )
    author = models.ForeignKey(
        related_name = 'following'
    )

yatube/posts/forms.py
from django import forms
from posts.models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        

yatube/posts/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.views.decorators.cache import cache_page
# from yatube.posts.models import Comment

from yatube.settings import PAGE_NUM
from posts.models import Post, Group, User
from django.core.paginator import Paginator
# from posts.forms import PostForm
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from posts.forms import PostForm, CommentForm


@cache_page(20)
def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, PAGE_NUM)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    template = 'posts/index.html'
    posts = Post.objects.all()
    context = {
        'posts': posts,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    title = str(group)
    description = group.description
    paginator = Paginator(posts, PAGE_NUM)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    template = 'posts/group_list.html'
    context = {
        'description': description,
        'group': group,
        'posts': posts,
        'page_obj': page_obj,
        'title': title,
    }
    return render(request, template, context)


def profile(request, username):
    username = get_object_or_404(User, username=username)
    posts = username.posts.all()
    paginator = Paginator(posts, PAGE_NUM)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    posts_num = posts.count()
    title = 'Профайл пользователя ' + str(username.get_full_name())
    context = {
        'username': username,
        'title': title,
        'posts_num': posts_num,
        'page_obj': page_obj,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    posts_num = post.author.posts.all().count()
    title = str(post)
    form = CommentForm()
    comments = post.comments.all()
    context = {
        'post': post,
        'posts_num': posts_num,
        'title': title,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
@csrf_exempt
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    groups = Group.objects.all()
    if form.is_valid():
        form = form.save(commit=False)
        form.author = request.user
        form.save()
        return redirect('posts:profile', form.author)
    context = {
        'form': form,
        'groups': groups,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(request.POST or None, instance=post)
    groups = Group.objects.all()
    if form.is_valid():
        form = form.save(False)
        form.author = request.user
        form.save()
        return redirect('posts:post_detail', post_id)
    context = {
        'form': form,
        'post': post,
        'is_edit': True,
        'groups': groups,
    }
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
        for comm in post.comments.all():
            print(comm.text)    
    return redirect('posts:post_detail', post_id=post_id)

yatube/templates/posts/comments.html
{% load user_filters %}
{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
        <p>
         {{ comment.text }}
        </p>
      </div>
    </div>
{% endfor %}

yatube/templates/posts/create_post.html
{% extends 'base.html' %} 
{% load thumbnail %}
      {% block title %}
        {% if is_edit%}
          Редактировать 
        {% else %}
          Добавить 
        {% endif %}
        запись
      {% endblock %}
      {% block content %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                {%if is_edit%}       
                  Редактирование поста
                {% else %}
                  Новый пост
                {% endif %}
              </div>
              <div class="card-body">        
                <form method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                  {% comment %} {% for field in form %} {% endcomment %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      {{ form.text.label }}           
                      <span class="required text-danger" >*</span>                  
                    </label>
                    <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text" >{% if is_edit %}{{ form.text.value }}{% endif %}</textarea>                
                    <small id="id_text-help" class="form-text text-muted">
                      {{ form.text.help_text }} 
                    </small>                  
                  </div>            
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      {{ form.group.label }}                 
                    </label>
                    <select name="group" class="form-control" id="id_group">
                      <option value="" selected></option>
                      {% for group in groups %}
                        <option value={{ group.id }}> {{ group.title }}</option>
                      {% endfor %}
                    </select>
                    <small id="id_group-help" class="form-text text-muted">
                      {{ form.group.help_text }}
                    </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_image">
                      {{ form.image.label }}                 
                    </label>
                    {{ form.image }}
                    <small id="id_image-help" class="form-text text-muted">
                      {{ form.image.help_text }}
                    </small>
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %}
                    </button>
                  </div>
                  {% comment %} {% endfor %} {% endcomment %}
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %} 
{% load thumbnail %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
  <div>
    <h1> {{ title }} </h1>
    <p>{{ description }}</p>
      {% for post in page_obj %}
        <ul>
          <li>Автор: {{ post.author.get_full_name }}</li>
          <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
          <li>{{ post.pk }}</li>
        </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
           <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
        <p>{{ post.text }}</p>    
        {% if not forloop.last %}
          <hr />
        {% endif %}
      {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %} 

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
{% load cache %}
{% cache 500 sidebar %}
  {% for post in page_obj %}
    <ul>
     <li>
       Автор: {{ post.author.get_full_name }}
      </li>
      <li>
       Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
   </ul>
   {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
   <p>{{ post.text }}</p>  
   {% if post.group %}   
    <a href="{% url 'posts:slug' post.group.slug %}">все записи группы</a>
    {% endif %} 
   {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% endcache %} 
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}{{title}}{% endblock %}
{% block content %}

<div class="row">
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item"> Дата публикации: {{ post.pub_date }}</li> 
      {% if post.group.slug %} 
      <li class="list-group-item"> Группа: {{ post.group.title }}
        <a href="{% url 'posts:slug' post.group.slug %}">все записи группы</a>
      </li> 
      {% endif %} 
      <li class="list-group-item"> Автор: {{ post.author.get_full_name }}</li>
      <li class="list-group-item d-flex justify-content-between align-items-center"> Всего постов автора: <span>{{ posts_num }}</span></li>
      <li class="list-group-item"><a href="{% url 'posts:profile' post.author.username %}">Все посты пользователя</a></li>
    </ul>
  </aside>
  <article>
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }} 
        {% comment %} <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a> {% endcomment %}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text.label }}</p>
    <a href="{% url 'posts:post_detail' post.pk %}">Подробная информация</a>
  </article>
  <article class="col-12 col-md-9">
    <p>
    {% comment %} {{ post.text|wordwrap:78 }} {% endcomment %}
    </p>
    {% if request.user.is_authenticated and request.user == post.author %}
      <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
        Редактировать запись
    </a>
    {% endif %}
    {% include 'posts/comments.html' %}
  </article>
</div> 
{% endblock %}  

yatube/templates/posts/profile.html
{% extends 'base.html' %} 
{% block title %}{{ title }}{% endblock %} 
{% block content %}
{% load thumbnail %}

<div class="container py-5">
  <h1>Все посты пользователя {{ username.get_full_name }}</h1>
  <h3>Всего постов: {{ posts_num }}</h3>
  <hr />
  {% for post in page_obj %}
    <ul>
    <article>
      <ul>
        <li>Автор: {{post.author.get_full_name}}</li>
        <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text }}</p>
      <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
    </article>
    {% if post.group.slug %}
      <a href="{% url 'posts:slug' post.group.slug %}">все записи группы</a>
    {% endif %}
  </ul>
  {% if not forloop.last %}
    <hr />
  {% endif %} 
  {% endfor %} 
  {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}